version: '3.8'

services:
  postgresql:
    container_name: ms_pg_sql
    image: postgres:latest
    environment:
      POSTGRES_USER: amu
      POSTGRES_PASSWORD: quan2108
      POSTGRES_DB: mydatabase
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgresql

  mongodb:
    container_name: mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: amu
      MONGO_INITDB_ROOT_PASSWORD: amu
    networks:
      - microservices-net
    restart: unless-stopped

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=amu
      - ME_CONFIG_MONGODB_ADMINPASSWORD=amu
      - ME_CONFIG_MONGODB_SERVER=mongo_db
    networks:
      - microservices-net
    depends_on:
      - mongodb

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER ID: 1        # ID của Zookeeper trong cluster (nếu có nhiều node Zookeeper)
      ZOOKEEPER_CLIENT_PORT: 2181     # Port mà client sẽ kết nối tới Zookeeper
      ZOOKEEPER_TICK_TIME: 2000       # Thời gian tick (mỗi tick là một đơn vị thời gian cho Zookeeper)
    ports:
      - 22181:2181
    networks:
      - microservices-net
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper        # Kafka phụ thuộc vào Zookeeper để khởi động
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1   # Số lượng bản sao cho topic lưu offset
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT   # Giao thức bảo mật
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092    #client sẽ kết nối tới Kafka qua localhost:9092
    networks:
      - microservices-net

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
